### ISSUE TITLE
parameters with s0 (or other number) in their name get rewritten 

### ISSUE THREAD

**Issue by dkoes** [pysb/pysb#185]
Somewhere in the guts of odesolve, parameters with s0, s1, etc as part of their name gets rewritten with y.

```
from pysb import*
from pysb.integrate import odesolve
from pysb import bng
import numpy as np

Model()

Monomer('A')
Monomer('R')
Monomer('RA')

Parameter('A0', 1e-3)
Parameter('ks0', 230)
Parameter('ks1', 178)
Parameter('R0', 10000)

Initial(A(), A0)
Initial(R(), R0)

Rule('ARrule', A() + R() <> RA(), ks0, ks1)

print bng.generate_network(model)
t = np.linspace(0,600)
y = odesolve(model,t)
```

```
# Created by BioNetGen 2.2.6-stable
begin parameters
    1 A0   1.000000e-03  # Constant
    2 ks0  2.300000e+02  # Constant
    3 ks1  1.780000e+02  # Constant
    4 R0   1.000000e+04  # Constant
end parameters
begin species
    1 A() A0
    2 R() R0
    3 RA() 0
end species
begin reactions
    1 1,2 3 ks0 #ARrule
    2 3 1,2 ks1 #_reverse_ARrule
end reactions

capi_return is NULL
Call-back cb_f_in_dvode__user__routines failed.
Traceback (most recent call last):
  File "p.py", line 24, in <module>
    y = odesolve(model,t)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysb/integrate.py", line 515, in odesolve
    solver.run(param_values, y0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysb/integrate.py", line 383, in run
    self.y[i] = self.integrator.integrate(self.tspan[i]) # integration
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/integrate/_ode.py", line 393, in integrate
    self.f_params, self.jac_params)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/scipy/integrate/_ode.py", line 848, in run
    y1, t, istate = self.runner(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysb/integrate.py", line 189, in rhs
    _exec(code_eqs_py, locals())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysb/integrate.py", line 27, in _exec
    exec(code, locals)
  File "<p odes>", line 1, in <module>
NameError: name 'ky' is not defined
```

This happens even if s0 isn't the suffix.

**Comment by jmuhlich** [comment]
Right. Thanks for the catch, and the repro code is much appreciated. We do some transformations on the generated code using regexes, and @lh6 points out there's one that needs some `\b`'s in it to match whole words instead of fragments. Should be a quick fix.
