### ISSUE TITLE
pysb.tools.render_reactions malfunction (or something else regarding render_reaction.py)

### ISSUE THREAD

**Issue by glucksfall** [pysb/pysb#227]
Hello everyone,
I have a problem calling `pysb.tools.render_reactions` from terminal. I tested the command with some example files, and some did it right, and other did it wrong like the following output. This output was generated from a custom model, but I will retry some examples to tell you which are functional and which are not, hoping you could tell what to fix inside the model. Thank you.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pysb/bng.py", line 416, in execute
    "\n" +
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/pysb/tools/render_reactions.py", line 156, in <module>
    print(run(model))
  File "/usr/local/lib/python3.5/dist-packages/pysb/tools/render_reactions.py", line 78, in run
    pysb.bng.generate_equations(model)
  File "/usr/local/lib/python3.5/dist-packages/pysb/bng.py", line 557, in generate_equations
    lines = iter(generate_network(model,cleanup,verbose=verbose).split('\n'))
  File "/usr/local/lib/python3.5/dist-packages/pysb/bng.py", line 532, in generate_network
    bngfile.execute()
  File "/usr/local/lib/python3.5/dist-packages/pysb/bng.py", line 419, in execute
    raise BngInterfaceError(e)
pysb.bng.BngInterfaceError: a bytes-like object is required, not 'str'
```

**Comment by JamesPino** [comment]
Does this only happen with render_reactions?  It seems that bionetgen gives an error. The error is being mishandled in python3 by pysb.
It shouldn't be hard to fix the exception, I just can't seem to find a model that raises one where it fails. Once we fix this then we should be able to see your error.

Can you provide a model where you get this error? Did you find any pysb.examples that can reproduce this?

**Comment by glucksfall** [comment]
I linked wrongly bng2.pl. Now (some time ago, sorry) it's working perfectly
