### ISSUE TITLE
Documentation for pysb.simulator missing online

### ISSUE THREAD

**Issue by bgyori** [pysb/pysb#311]
The page http://pysb.readthedocs.io/en/latest/modules/simulator.html is currently blank. Looking at the build logs on readthedocs.io, looks like `dateutil.parser` is not found causing a failure in building simulator.rst.

```
/home/docs/checkouts/readthedocs.org/user_builds/pysb/checkouts/latest/doc/modules/integrate.rst:4: WARNING: autodoc: failed to import module u'pysb.integrate'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysb/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysb/checkouts/latest/pysb/integrate.py", line 2, in <module>
    from pysb.simulator import ScipyOdeSimulator
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysb/checkouts/latest/pysb/simulator/__init__.py", line 1, in <module>
    from .base import SimulatorException, SimulationResult
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysb/checkouts/latest/pysb/simulator/base.py", line 13, in <module>
    import dateutil.parser
ImportError: No module named dateutil.parser
/home/docs/checkouts/readthedocs.org/user_builds/pysb/checkouts/latest/doc/modules/simulator.rst:4: WARNING: autodoc: failed to import module u'pysb.simulator'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysb/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysb/checkouts/latest/pysb/simulator/__init__.py", line 1, in <module>
    from .base import SimulatorException, SimulationResult
  File "/home/docs/checkouts/readthedocs.org/user_builds/pysb/checkouts/latest/pysb/simulator/base.py", line 13, in <module>
    import dateutil.parser
ImportError: No module named dateutil.parser
```

**Comment by alubbock** [comment]
@bgyori Thanks for the report. I noticed this a couple of weeks ago and created PR #305, which is currently awaiting review. Good to open an issue for this while that PR is pending though, in case anyone else comes across the problem.

**Comment by bgyori** [comment]
Okay, I didn't notice the connection, thanks!

**Comment by bgyori** [comment]
Actually, do the additional mocks in PR #305 really resolve this problem?

**Comment by alubbock** [comment]
No, turns out it doesn't fix it. I'll add `dateutil.parser` to the Sphinx mocks too. My apologies.

**Comment by alubbock** [comment]
This is now fixed. It should be a less severe issue should it occur again, now that readthedocs shows the release version of PySB by default, rather than development version.
