### ISSUE TITLE
new version of pysb with gpu_ssa 

### ISSUE THREAD

**Issue by junhag2** [pysb/pysb#569]
I know that there is a specific version of pysb that is capable of simulating with GPU with ssa method (1.11.0+170.g43c73d5)
It works no problem with python 3.7, but when I tried it with python 3.8.0, it reports a bug (please find the error message below).
It seems that the object return from any simulator (BngSimulator,CudaSSASimulator,etc.,) would raise such TypeError.
Newer version of pysb (1.14.0) does not report such error, but it does not contain the CudaSSASimulator.

Is there any version of pysb with GPU_ssa function that works for python 3.8 or above?
Thank you

Traceback (most recent call last):
  File "E:\python\lib\site-packages\IPython\core\interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-2f8ca271b85a>", line 1, in <module>
    result = x.run(number_sim=100)
  File "E:\python\lib\site-packages\pysb\simulator\cuda_ssa.py", line 249, in run
    return SimulationResult(self, tout, result[:self.num_sim, :, :])
  File "E:\python\lib\site-packages\pysb\simulator\base.py", line 744, in __init__
    self._model = copy.deepcopy(simulator._model)
  File "E:\python\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "E:\python\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "E:\python\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "E:\python\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "E:\python\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "E:\python\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "E:\python\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "E:\python\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "E:\python\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "E:\python\lib\copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "E:\python\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "E:\python\lib\copy.py", line 264, in _reconstruct
    y = func(*args)
  File "E:\python\lib\copyreg.py", line 97, in __newobj_ex__
    return cls.__new__(cls, *args, **kwargs)
TypeError: __new__() got an unexpected keyword argument 'real'

**Comment by JamesPino** [comment]
Sorry I didn't see this before. I recently committed updates to the branch for the PR to be complete. That branch works currently.
