### ISSUE TITLE
`test_bng_boolean_multiply_number` fails with SymPy 1.12

### ISSUE THREAD

**Issue by himoto** [pysb/pysb#577]
When running tests with the latest [sympy 1.12](https://github.com/sympy/sympy/releases/tag/sympy-1.12), I got the following error message.

```
======================================================================
ERROR: pysb.tests.test_bng.test_bng_boolean_multiply_number
----------------------------------------------------------------------
ValueError: Error from parse_expr with transformed code: <code object <module> at 0x7f37c5f52450, file "<string>", line 1>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/pysb/lib/python3.9/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/runner/work/pysb/pysb/build/lib/pysb/tests/test_bng.py", line 425, in test_bng_boolean_multiply_number
    assert parse_bngl_expr('(2 > 1) * 4') == 4
  File "/home/runner/work/pysb/pysb/build/lib/pysb/bng.py", line 946, in parse_bngl_expr
    expr = sympy_parser.parse_expr(text, *args, transformations=trans,
  File "/usr/share/miniconda/envs/pysb/lib/python3.9/site-packages/sympy/parsing/sympy_parser.py", line 1087, in parse_expr
    raise e from ValueError(f"Error from parse_expr with transformed code: {code!r}")
  File "/usr/share/miniconda/envs/pysb/lib/python3.9/site-packages/sympy/parsing/sympy_parser.py", line 1078, in parse_expr
    rv = eval_expr(code, local_dict, global_dict)
  File "/usr/share/miniconda/envs/pysb/lib/python3.9/site-packages/sympy/parsing/sympy_parser.py", line 906, in eval_expr
    expr = eval(
  File "<string>", line 1, in <module>
  File "/usr/share/miniconda/envs/pysb/lib/python3.9/site-packages/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/usr/share/miniconda/envs/pysb/lib/python3.9/site-packages/sympy/core/operations.py", line 64, in __new__
    raise TypeError("Relational cannot be used in %s" % cls.__name__)
TypeError: Relational cannot be used in Mul
```
If I use `sympy<1.12`, it threw SymPyDeprecationWarning but not TypeError.

**Reproducibility:**
- OS: Ubuntu 22.04
- Python version: 3.9
- PySB version: 1.15
- SymPy version: 1.12

**Comment by jmuhlich** [comment]
Thanks for the report. It looks like sympy 1.12 is not released yet, but we will try to get this pysb issue fixed before then.

**Comment by jmuhlich** [comment]
Addressed for now in #581, but we'll leave this issue open as a reminder to fix the underlying issue for sympy 1.12 compatibility.

**Comment by dweindl** [comment]
Hi, pysb still requires sympy<1.12. [sympy 1.13](https://github.com/sympy/sympy/releases/tag/1.13.0rc3) is close to be released. It would be great if pysb could at least work with sympy 1.12.1 which is the first numpy>=2.0 compatible sympy release.

**Comment by jmuhlich** [comment]
Thanks for the reminder. #599 should fix the issue. Once that's merged I'll release a new pysb version.
